pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        /*
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
		stage('Jacoco') {
            steps {
		       jacoco()
			}
		}
		*/
		stage('Image') {
		    steps {
		        sh 'mvn docker:build'
		    }
		}
		/*
        stage('Deploy') {
            steps {
                withEnv(['JENKINS_NODE_COOKIE=dontkillme']){
					sh './jenkins/startup.sh'
				}
            }
        }
        */
    }
}
