pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        /*
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
		stage('Jacoco') {
            steps {
		       jacoco()
			}
		}
		*/
		/*
		stage('Image') {
		    steps {
		        sh 'mvn docker:build'
		    }
		}
		stage('Push') {
            steps {
       	        sh 'mvn docker:push'
       	   }
       	}*/
        stage('Deploy') {
            steps {
                withEnv(['JENKINS_NODE_COOKIE=dontkillme']){
					sh 'docker service create --replicas 1 --name eureka -p 8080:8080 registry.cn-hangzhou.aliyuncs.com/nju_oasis/eureka:0.0.1'
				}
            }
        }
    }
}
